version: '3'

services:
  server:
    image: centos:latest
    tty: true
    networks:
      - my_network
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      TZ: 'Asia/Tokyo'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./:/tmp
    ports:
      - 3800:3306
    networks:
      - my_network
networks:
  my_network: